export type ZoneKey = "HIALEAH" | "MIAMI" | "HOMESTEAD" | "DORAL" | "BROWARD" | "OTROS";
export const ZONE_EMOJI: Record<ZoneKey, string> = { HIALEAH: "🟡", MIAMI: "🔵", HOMESTEAD: "🟢", DORAL: "🟠", BROWARD: "🟣", OTROS: "⚪" };
export const ZONE_COLOR: Record<ZoneKey, string> = { HIALEAH: "#ffbe00", MIAMI: "#5ec8ff", HOMESTEAD: "#00dc85", DORAL: "#ff9040", BROWARD: "#b98cff", OTROS: "#8da4c9" };
export const ZONE_ORDER: ZoneKey[] = ["HIALEAH", "MIAMI", "HOMESTEAD", "DORAL", "BROWARD", "OTROS"];
const HIALEAH_ZIPS = new Set(["33010","33011","33012","33013","33014","33015","33016","33017","33018","33054"]);
const DORAL_ZIPS = new Set(["33122","33166","33172","33178","33182","33191","33195","33198"]);
const HOMESTEAD_ZIPS = new Set(["33030","33031","33032","33033","33034","33035","33039","33090","33092"]);
function isBrowardZip(z: string): boolean { if (!z) return false; const n = parseInt(z.slice(0,5),10); if (!Number.isFinite(n)) return false; if (n>=33004 && n<=33009) return true; if (n>=33019 && n<=33029) return true; if (n>=33060 && n<=33097) return true; if (n>=33301 && n<=33499) return true; return false; }
function extractZip(address: string, zipField: string): string { if (zipField) return String(zipField).trim().slice(0,5); const m = String(address||"").match(/\b(\d{5})(-\d{4})?\b/); return m ? m[1] : ""; }
export function deriveCity(address: string, zip?: string, city?: string): ZoneKey { const upper = String(city||"").toUpperCase(); if (upper.includes("HIALEAH")) return "HIALEAH"; if (upper.includes("HOMESTEAD") || upper.includes("FLORIDA CITY")) return "HOMESTEAD"; if (upper.includes("DORAL")) return "DORAL"; if (upper.includes("LAUDERDALE") || upper.includes("HOLLYWOOD") || upper.includes("PEMBROKE") || upper.includes("MIRAMAR") || upper.includes("DAVIE") || upper.includes("PLANTATION") || upper.includes("SUNRISE") || upper.includes("CORAL SPRINGS") || upper.includes("POMPANO") || upper.includes("WESTON")) return "BROWARD"; if (upper === "MIAMI" || upper.includes("MIAMI GARDENS") || upper.includes("MIAMI LAKES") || upper.includes("MIAMI BEACH") || upper.includes("MIAMI SPRINGS")) return "MIAMI"; const z = extractZip(address||"", zip||""); if (z) { if (HIALEAH_ZIPS.has(z)) return "HIALEAH"; if (DORAL_ZIPS.has(z)) return "DORAL"; if (HOMESTEAD_ZIPS.has(z)) return "HOMESTEAD"; if (isBrowardZip(z)) return "BROWARD"; const n = parseInt(z,10); if (n>=33101 && n<=33299) return "MIAMI"; } const addrUp = String(address||"").toUpperCase(); if (addrUp.includes("HIALEAH")) return "HIALEAH"; if (addrUp.includes("HOMESTEAD")) return "HOMESTEAD"; if (addrUp.includes("DORAL")) return "DORAL"; if (addrUp.includes("MIRAMAR") || addrUp.includes("HOLLYWOOD") || addrUp.includes("PEMBROKE") || addrUp.includes("LAUDERDALE")) return "BROWARD"; return "OTROS"; }
