// @ts-nocheck
import { useCallback, useEffect, useMemo, useState } from 'react';
import * as XLSX from 'xlsx';
import { sb } from '../../../config/supabase';
import { APP_FIRST_DATE } from '../../../config/constants';
import { getTechName, getTechsByRegion } from '../../../legacy/data';
import { OpsButton, OpsCard, OpsEmpty, OPS, fieldStyle } from '../../operations/components/OperationsPrimitives';

type PeriodMode = 'day' | 'week' | 'month' | 'year' | 'custom';
type FactRow = { id?: string; region?: string; date?: string; tech_id?: string; tech_name?: string; job_id?: string; address?: string; city?: string; zip?: string; phone?: string; type?: string; status?: string; status_group?: 'completed' | 'not_done' | 'pending'; reason?: string; notes?: string; pay_code?: string; pay_total?: number; source?: string; search_text?: string; _priority?: number; };

const td = { padding: '8px 6px', borderBottom: `1px solid ${OPS.border}`, color: OPS.text };
function todayIso(){ return new Date().toLocaleDateString('en-CA'); }
function iso(d:Date){ return d.toLocaleDateString('en-CA'); }
function parseLocalDate(value:string){ const [y,m,day]=String(value||todayIso()).split('-').map(Number); return new Date(y||new Date().getFullYear(),(m||1)-1,day||1); }
function startOfWeek(d:Date){ const x=new Date(d); const day=x.getDay(); const diff=(day===0?-6:1-day); x.setDate(x.getDate()+diff); return x; }
function endOfWeek(d:Date){ const x=startOfWeek(d); x.setDate(x.getDate()+6); return x; }
function startOfMonth(d:Date){ return new Date(d.getFullYear(),d.getMonth(),1); }
function endOfMonth(d:Date){ return new Date(d.getFullYear(),d.getMonth()+1,0); }
function startOfYear(d:Date){ return new Date(d.getFullYear(),0,1); }
function endOfYear(d:Date){ return new Date(d.getFullYear(),11,31); }
function clampDate(value:any){ return String(value||'').slice(0,10); }
function money(n:any){ return Number(n||0).toLocaleString(undefined,{style:'currency',currency:'USD',maximumFractionDigits:0}); }
function norm(v:any){ return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim(); }
function includesAny(hay:string, needles:string[]){ return needles.some(n=>n && hay.includes(norm(n))); }
function pct(n:number,d:number){ return d?Math.round((n/d)*100):0; }
function statusGroup(status:any):FactRow['status_group']{ const s=norm(status).replace(/[\s-]/g,'_'); if(['done','completed','complete','closed','resolved'].includes(s))return 'completed'; if(['notdone','not_done','not_completed','notcompleted','cancelled','canceled','failed','fail','customer_absent','no_access','open'].includes(s))return 'not_done'; return 'pending'; }
function canonicalReason(row:any){ return row.reason || row.latest_reason || row.original_reason || row.status_reason || row.not_done_reason || row.job_note || row.notes || row.latest_notes || row.note || ''; }
function cleanPay(row:any){ return row.pay_code || row.billing_code || row.billing || row.code || ''; }
function cleanPayTotal(row:any){ return Number(row.pay_total ?? row.pay ?? row.amount ?? row.total ?? 0) || 0; }
function rowDate(row:any, fallback?:string){ return clampDate(row.date || row.source_route_date || row.route_date || row.last_not_done_date || row.first_not_done_date || row.created_at || row.updated_at || fallback || ''); }
function rowTech(row:any){ return String(row.tech_id || row.technician_id || row.latest_technician_id || row.source_technician_id || row.techNumber || row.tech_number || '').trim(); }
function rowTechName(row:any, techId:string){ return row.tech_name || row.technician_name || row.latest_technician_name || row.name || (techId?getTechName(techId):'Unassigned'); }
function rowSearchText(row:any, fact:FactRow){ return [fact.tech_id,fact.tech_name,fact.job_id,fact.address,fact.city,fact.zip,fact.phone,fact.type,fact.status,fact.status_group,fact.reason,fact.notes,fact.pay_code,fact.pay_total,fact.source,row.work_type,row.current_status,row.latest_reason,row.original_reason,row.latest_notes,row.job_note,row.notes].map(norm).join(' | '); }
function mapRow(row:any, source:string, fallbackDate?:string, priority=1):FactRow{ const techId=rowTech(row); const fact:FactRow={ id:String(row.id || `${source}-${rowDate(row,fallbackDate)}-${row.job_id || row.address || Math.random()}`), region:row.region, date:rowDate(row,fallbackDate), tech_id:techId || 'unassigned', tech_name:rowTechName(row,techId), job_id:String(row.job_id || row.work_order || row.ticket || '').trim(), address:row.address || row.service_address || row.location || '', city:row.city || '', zip:row.zip || row.zip_code || row.zone || '', phone:row.phone || row.phone_number || '', type:row.type || row.work_type || row.service_type || '', status:row.status || row.current_status || 'pending', reason:canonicalReason(row), notes:row.notes || row.job_note || row.latest_notes || '', pay_code:cleanPay(row), pay_total:cleanPayTotal(row), source, _priority:priority }; fact.status_group=statusGroup(fact.status); fact.search_text=rowSearchText(row,fact); return fact; }
function flattenSnapshot(record:any, relation:string, priority:number){ const date=clampDate(record.date || record.route_date || record.created_at); const snapshot=Array.isArray(record.snapshot)?record.snapshot:Array.isArray(record.jobs)?record.jobs:[]; return snapshot.map((job:any,idx:number)=>mapRow({...job,region:job.region||record.region,id:job.id||`${relation}-${date}-${idx}`},relation,date,priority)); }
function dedupeFacts(rows:FactRow[]){ const sorted=[...rows].sort((a,b)=>Number(b._priority||0)-Number(a._priority||0)); const map=new Map<string,FactRow>(); sorted.forEach((r,idx)=>{ const key=[r.region||'',r.date||'',r.tech_id||'',r.job_id||r.address||idx,r.status_group||'',r.pay_code||'',r.reason||''].map(norm).join('|'); if(!map.has(key))map.set(key,r); }); return [...map.values()]; }
function periodRange(mode:PeriodMode, anchor:string, customFrom:string, customTo:string){ const d=parseLocalDate(anchor||todayIso()); if(mode==='day')return {from:iso(d),to:iso(d),label:iso(d)}; if(mode==='week'){ const a=startOfWeek(d),b=endOfWeek(d); return {from:iso(a),to:iso(b),label:`${iso(a)} → ${iso(b)}`}; } if(mode==='month'){ const a=startOfMonth(d),b=endOfMonth(d); return {from:iso(a),to:iso(b),label:d.toLocaleString('default',{month:'long',year:'numeric'})}; } if(mode==='year'){ const a=startOfYear(d),b=endOfYear(d); return {from:iso(a),to:iso(b),label:String(d.getFullYear())}; } return {from:customFrom||APP_FIRST_DATE,to:customTo||todayIso(),label:`${customFrom||APP_FIRST_DATE} → ${customTo||todayIso()}`}; }
function weekKey(date:string){ const d=parseLocalDate(date); const a=startOfWeek(d),b=endOfWeek(d); return `${iso(a)} → ${iso(b)}`; }
function bucketKey(row:FactRow, mode:PeriodMode){ const d=row.date||''; if(mode==='day')return d; if(mode==='week')return weekKey(d); if(mode==='month')return d.slice(0,7); if(mode==='year')return d.slice(0,4); return d; }
function extractTechFromPhrase(input:string){ const matches=String(input||'').match(/\b\d{4,6}\b/g)||[]; return matches[0]||''; }
function tokenizeQuestion(input:string){ const filler=new Set(['cuantos','cuantas','cuanto','cuanta','tiene','tienen','reporto','reporto?','reporte','reportar','hizo','el','la','los','las','del','de','por','para','tech','tecnico','tecnicos','numero','how','many','does','did','has','have','reported','report','the','a','an','jobs','job']); return norm(input).replace(/\b\d{4,6}\b/g,' ').split(/[^a-z0-9#]+/).map(x=>x.trim()).filter(x=>x && !filler.has(x) && x.length>1); }
function expandTerms(raw:string){ const n=norm(raw); const terms=new Set<string>(); tokenizeQuestion(raw).forEach(t=>terms.add(t)); if(n.includes('customer absent')||n.includes('customer ausente')||n.includes('cliente ausente'))['customer absent','customer ausente','cliente ausente','not home','no home','no access','no acceso','absent','ausente'].forEach(t=>terms.add(t)); if(n.includes('misil')||n.includes('missil')||n.includes('missed')||n.includes('miss'))['misil','missil','missed','miss','missing'].forEach(t=>terms.add(t)); if(n.includes('811'))terms.add('811'); return [...terms]; }
function aggregate(rows:FactRow[]){ const completed=rows.filter(r=>r.status_group==='completed'); const notDone=rows.filter(r=>r.status_group==='not_done'); const pending=rows.filter(r=>r.status_group==='pending'); const value=completed.reduce((s,r)=>s+Number(r.pay_total||0),0); const uniqueJobs=new Set(rows.map(r=>r.job_id).filter(Boolean)).size; return {total:rows.length,uniqueJobs,completed:completed.length,notDone:notDone.length,pending:pending.length,value,completionRate:pct(completed.length,rows.length),failRate:pct(notDone.length,rows.length)}; }
function exportRows(rows:FactRow[], filename:string){ const data=rows.map(r=>({Date:r.date,Tech:r.tech_id,'Tech Name':r.tech_name,'Job ID':r.job_id,Status:r.status_group,RawStatus:r.status,Address:r.address,City:r.city,ZIP:r.zip,Phone:r.phone,Type:r.type,Reason:r.reason,Notes:r.notes,'Billing Code':r.pay_code,Value:r.pay_total,Source:r.source})); const ws=XLSX.utils.json_to_sheet(data); const wb=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb,ws,'Tech Stats'); XLSX.writeFile(wb,filename); }
async function safe(label:string,promise:any){ try{ const res=await promise; if(res?.error)return {data:[],warning:`${label}: ${res.error.message||res.error}`}; return {data:res?.data||[],warning:''}; }catch(error:any){ return {data:[],warning:`${label}: ${error?.message||String(error)}`}; } }

export default function DispatchTechnicianStats({region,lang}:{region:string;lang:string}){
  const es=lang==='es'; const today=todayIso();
  const [period,setPeriod]=useState<PeriodMode>('week'); const [anchor,setAnchor]=useState(today); const [customFrom,setCustomFrom]=useState(APP_FIRST_DATE); const [customTo,setCustomTo]=useState(today); const [techSearch,setTechSearch]=useState(''); const [phrase,setPhrase]=useState(''); const [statusFilter,setStatusFilter]=useState('all'); const [rows,setRows]=useState<FactRow[]>([]); const [loading,setLoading]=useState(false); const [warnings,setWarnings]=useState<string[]>([]); const [selectedTech,setSelectedTech]=useState('');
  const range=useMemo(()=>periodRange(period,anchor,customFrom,customTo),[period,anchor,customFrom,customTo]); const phraseTech=useMemo(()=>extractTechFromPhrase(phrase),[phrase]); const phraseTerms=useMemo(()=>expandTerms(phrase),[phrase]); const effectiveTechQuery=(techSearch||phraseTech||selectedTech||'').trim();

  const load=useCallback(async()=>{ setLoading(true); setWarnings([]); const {from,to}=range; const [routes,completed,cancelled,reports,pool,daily,archive]=await Promise.all([
    safe('routes', (()=>{let q=sb.from('routes').select('*').gte('date',from).lte('date',to).limit(4000); if(region)q=q.eq('region',region); return q;})()),
    safe('completed_jobs', (()=>{let q=sb.from('completed_jobs').select('*').gte('date',from).lte('date',to).limit(4000); if(region)q=q.eq('region',region); return q;})()),
    safe('cancelled_jobs', (()=>{let q=sb.from('cancelled_jobs').select('*').gte('source_route_date',from).lte('source_route_date',to).limit(4000); if(region)q=q.eq('region',region); return q;})()),
    safe('not_done_reports', (()=>{let q=sb.from('not_done_reports').select('*').gte('date',from).lte('date',to).limit(4000); if(region)q=q.eq('region',region); return q;})()),
    safe('not_done_pool', (()=>{let q=sb.from('not_done_pool').select('*').limit(2000); if(region)q=q.eq('region',region); return q;})()),
    safe('daily_route_snapshots', (()=>{let q=sb.from('daily_route_snapshots').select('date,region,snapshot').gte('date',from).lte('date',to).limit(366); if(region)q=q.eq('region',region); return q;})()),
    safe('archived_routes', (()=>{let q=sb.from('archived_routes').select('route_date,region,snapshot').gte('route_date',from).lte('route_date',to).limit(366); if(region)q=q.eq('region',region); return q;})()),
  ]);
    const facts=[...(routes.data||[]).map((r:any)=>mapRow(r,'routes',undefined,6)),...(completed.data||[]).map((r:any)=>mapRow({...r,status:r.status||'done'},'completed_jobs',undefined,5)),...(cancelled.data||[]).map((r:any)=>mapRow({...r,date:r.source_route_date,status:r.status||'cancelled'},'cancelled_jobs',undefined,4)),...(reports.data||[]).map((r:any)=>mapRow({...r,status:r.status||'not_done'},'not_done_reports',undefined,4)),...(pool.data||[]).map((r:any)=>mapRow({...r,date:r.last_not_done_date||r.first_not_done_date,status:r.current_status||'open',tech_id:r.latest_technician_id||r.source_technician_id,reason:r.latest_reason||r.original_reason,notes:r.latest_notes,type:r.work_type},'not_done_pool',undefined,3)),...(daily.data||[]).flatMap((r:any)=>flattenSnapshot(r,'daily_route_snapshots',2)),...(archive.data||[]).flatMap((r:any)=>flattenSnapshot(r,'archived_routes',1))].filter((r:FactRow)=>!r.date || (r.date>=from&&r.date<=to));
    setRows(dedupeFacts(facts)); setWarnings([routes.warning,completed.warning,cancelled.warning,reports.warning,pool.warning,daily.warning,archive.warning].filter(Boolean)); setLoading(false); },[range.from,range.to,region]);
  useEffect(()=>{load();},[load]);

  const filtered=useMemo(()=>{ const tq=norm(effectiveTechQuery); const terms=phraseTerms; const sq=norm(techSearch); return rows.filter(r=>{ const techText=norm([r.tech_id,r.tech_name,getTechName(r.tech_id||'')].join(' ')); const matchTech=!tq || techText.includes(tq); const matchStatus=statusFilter==='all'||r.status_group===statusFilter; const matchPhrase=terms.length===0 || includesAny(r.search_text||'',terms); const matchPlainTechSearch=!sq || techText.includes(sq) || norm(r.search_text).includes(sq); return matchTech && matchStatus && matchPhrase && matchPlainTechSearch; }); },[rows,effectiveTechQuery,phraseTerms,statusFilter,techSearch]);
  const summary=useMemo(()=>aggregate(filtered),[filtered]);
  const byTech=useMemo(()=>{ const map=new Map<string,any>(); filtered.forEach(r=>{ const id=r.tech_id||'unassigned'; const item=map.get(id)||{tech_id:id,tech_name:r.tech_name||getTechName(id),rows:[]}; item.rows.push(r); map.set(id,item); }); return [...map.values()].map(x=>({...x,...aggregate(x.rows)})).sort((a,b)=>b.total-a.total||b.value-a.value); },[filtered]);
  const byBilling=useMemo(()=>{ const map=new Map<string,any>(); filtered.filter(r=>r.pay_code||r.pay_total).forEach(r=>{ const code=r.pay_code||'No code'; const item=map.get(code)||{code,count:0,value:0,techs:new Set<string>()}; item.count+=1; item.value+=Number(r.pay_total||0); if(r.tech_id)item.techs.add(r.tech_id); map.set(code,item); }); return [...map.values()].map(x=>({...x,techCount:x.techs.size})).sort((a,b)=>b.value-a.value||b.count-a.count); },[filtered]);
  const byReason=useMemo(()=>{ const map=new Map<string,any>(); filtered.filter(r=>r.status_group==='not_done'||r.reason).forEach(r=>{ const reason=(r.reason||r.status||'No reason').trim()||'No reason'; const key=reason.length>48?reason.slice(0,48)+'…':reason; const item=map.get(key)||{reason:key,count:0,techs:new Set<string>()}; item.count+=1; if(r.tech_id)item.techs.add(r.tech_id); map.set(key,item); }); return [...map.values()].map(x=>({...x,techCount:x.techs.size})).sort((a,b)=>b.count-a.count).slice(0,12); },[filtered]);
  const byPeriod=useMemo(()=>{ const map=new Map<string,any>(); const breakdownMode=period==='custom'?'week':period; filtered.forEach(r=>{ const key=bucketKey(r,breakdownMode); const item=map.get(key)||{period:key,rows:[]}; item.rows.push(r); map.set(key,item); }); return [...map.values()].map(x=>({...x,...aggregate(x.rows)})).sort((a,b)=>String(a.period).localeCompare(String(b.period))); },[filtered,period]);
  const answer=useMemo(()=>{ if(!phrase.trim())return ''; const t=phraseTech||effectiveTechQuery; const terms=phraseTerms.join(', ')||phrase.trim(); const techLabel=t?`Tech #${t}`:(es?'Todos los técnicos':'All techs'); return `${techLabel} · ${terms} · ${range.label}: ${summary.total} ${es?'coincidencias':'matches'} (${summary.completed} done, ${summary.notDone} not done, ${summary.pending} pending) · ${money(summary.value)}`; },[phrase,phraseTech,effectiveTechQuery,phraseTerms,range.label,summary,es]);
  const setQuick=(mode:PeriodMode)=>{setPeriod(mode);setAnchor(todayIso());};

  return <div style={{display:'flex',flexDirection:'column',gap:12}}>
    <OpsCard>
      <div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap',alignItems:'flex-start'}}><div><div style={{fontSize:17,fontWeight:900,color:OPS.text}}>📊 {es?'Búsqueda y estadísticas por técnico':'Technician search + statistics'}</div><div style={{fontSize:11,color:OPS.dim,marginTop:4}}>{es?'Pregunta por técnico, periodo, frase, billing code, trabajos completados, fallados o pendientes.':'Ask by technician, period, phrase, billing code, completed, failed or pending jobs.'}</div></div><div style={{display:'flex',gap:6,flexWrap:'wrap'}}>{(['day','week','month','year'] as PeriodMode[]).map(m=><button key={m} onClick={()=>setQuick(m)} style={{background:period===m?'#00b8f522':'#162e58',border:`1px solid ${period===m?OPS.blue:OPS.border}`,borderRadius:8,padding:'7px 9px',color:period===m?OPS.blue:OPS.dim,fontSize:10,fontWeight:900,cursor:'pointer'}}>{m.toUpperCase()}</button>)}<button onClick={()=>setPeriod('custom')} style={{background:period==='custom'?'#9d5fff22':'#162e58',border:`1px solid ${period==='custom'?OPS.purple:OPS.border}`,borderRadius:8,padding:'7px 9px',color:period==='custom'?OPS.purple:OPS.dim,fontSize:10,fontWeight:900,cursor:'pointer'}}>CUSTOM</button></div></div>
      <div style={{display:'grid',gridTemplateColumns:'minmax(180px,1.25fr) minmax(160px,.9fr) 150px 150px 150px auto',gap:8,marginTop:12,alignItems:'center'}} className="tech-stats-filters"><input value={phrase} onChange={e=>setPhrase(e.target.value)} placeholder={es?'Pregunta: cuantos customer ausentes tiene el 6017':'Ask: how many customer absent for 6017'} style={fieldStyle}/><input value={techSearch} onChange={e=>{setTechSearch(e.target.value);setSelectedTech('');}} placeholder={es?'Nombre o número técnico':'Tech name or number'} style={fieldStyle}/>{period==='custom'?<input type="date" value={customFrom} onChange={e=>setCustomFrom(e.target.value)} style={fieldStyle}/>:<input type="date" value={anchor} onChange={e=>setAnchor(e.target.value)} style={fieldStyle}/>} {period==='custom'?<input type="date" value={customTo} onChange={e=>setCustomTo(e.target.value)} style={fieldStyle}/>:<div style={{...fieldStyle,color:OPS.dim,display:'flex',alignItems:'center'}}>{range.label}</div>}<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} style={fieldStyle}><option value="all">{es?'Todos':'All status'}</option><option value="completed">Completed</option><option value="not_done">Not done / failed</option><option value="pending">Pending</option></select><OpsButton onClick={load} disabled={loading}>{loading?'…':es?'Actualizar':'Refresh'}</OpsButton></div>
      <div style={{display:'flex',gap:6,flexWrap:'wrap',marginTop:10}}>{['customer absent 6017','misil 8804','811','no access','pending','JS:BURY'].map(example=><button key={example} onClick={()=>setPhrase(example)} style={{background:'#071327',border:`1px solid ${OPS.border}`,borderRadius:20,padding:'5px 8px',color:OPS.dim,fontSize:10,cursor:'pointer'}}>🔎 {example}</button>)}</div>
      {answer&&<div style={{marginTop:10,background:'#00b8f512',border:'1px solid #00b8f555',borderRadius:10,padding:'10px 12px',color:'#dbe8ff',fontSize:12}}><b style={{color:OPS.blue}}>{es?'Respuesta:':'Answer:'}</b> {answer}</div>}
      {warnings.length>0&&<div style={{marginTop:9,background:'#ffbe0012',border:'1px solid #ffbe0055',borderRadius:9,padding:'8px 10px',color:'#ffcf55',fontSize:10}}>⚠ {warnings.slice(0,3).join(' · ')}</div>}
    </OpsCard>

    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(145px,1fr))',gap:8}}>{[{l:es?'Total trabajos':'Total jobs',v:summary.total,c:OPS.blue},{l:es?'Únicos Job ID':'Unique job IDs',v:summary.uniqueJobs,c:OPS.purple},{l:es?'Completados':'Completed',v:summary.completed,c:OPS.green},{l:es?'No realizados / fallados':'Not done / failed',v:summary.notDone,c:OPS.red},{l:es?'Pendientes':'Pending',v:summary.pending,c:OPS.yellow},{l:es?'Valor billing':'Billing value',v:money(summary.value),c:OPS.green}].map(card=><div key={card.l} style={{background:OPS.card,border:`1px solid ${card.c}44`,borderRadius:12,padding:'11px 12px'}}><div style={{fontSize:22,fontWeight:900,color:card.c}}>{card.v}</div><div style={{fontSize:10,color:OPS.dim}}>{card.l}</div></div>)}</div>

    <div style={{display:'grid',gridTemplateColumns:'minmax(280px,1.2fr) minmax(260px,.8fr)',gap:12}} className="tech-stats-main-grid">
      <OpsCard><div style={{display:'flex',justifyContent:'space-between',gap:8,alignItems:'center',marginBottom:10,flexWrap:'wrap'}}><div><div style={{fontSize:15,fontWeight:900,color:OPS.text}}>{es?'Técnicos':'Technicians'}</div><div style={{fontSize:10,color:OPS.dim}}>{es?'Click para filtrar por un técnico.':'Click to filter one technician.'}</div></div><OpsButton tone="green" onClick={()=>exportRows(filtered,`tech_stats_${range.from}_${range.to}.xlsx`)}>⬇ XLSX</OpsButton></div>{loading?<div style={{padding:25,textAlign:'center',color:OPS.dim}}>Loading…</div>:byTech.length===0?<OpsEmpty>{es?'Sin resultados para estos filtros.':'No results for these filters.'}</OpsEmpty>:<div style={{display:'flex',flexDirection:'column',gap:8}}>{byTech.slice(0,80).map(t=>{ const active=selectedTech&&String(selectedTech)===String(t.tech_id); return <button key={t.tech_id} onClick={()=>{setSelectedTech(active?'':String(t.tech_id));setTechSearch(active?'':String(t.tech_id));}} style={{width:'100%',textAlign:'left',background:active?'#102b50':'#071327',border:`1px solid ${active?OPS.blue:OPS.border}`,borderRadius:12,padding:10,cursor:'pointer'}}><div style={{display:'grid',gridTemplateColumns:'minmax(130px,1fr) repeat(5,70px)',gap:8,alignItems:'center'}} className="tech-stats-tech-row"><div><div style={{fontWeight:900,color:OPS.text}}>{t.tech_name||getTechName(t.tech_id)} <span style={{color:OPS.blue}}>#{t.tech_id}</span></div><div style={{fontSize:10,color:OPS.dim}}>{t.completionRate}% completed · {t.failRate}% failed</div></div><Metric label="Total" value={t.total} color={OPS.blue}/><Metric label="Done" value={t.completed} color={OPS.green}/><Metric label="Failed" value={t.notDone} color={OPS.red}/><Metric label="Pending" value={t.pending} color={OPS.yellow}/><Metric label="Value" value={money(t.value)} color={OPS.green}/></div></button>})}</div>}</OpsCard>
      <div style={{display:'flex',flexDirection:'column',gap:12}}><OpsCard><div style={{fontSize:15,fontWeight:900,color:OPS.text,marginBottom:8}}>💳 {es?'Valor por billing code':'Value by billing code'}</div>{byBilling.length===0?<div style={{fontSize:11,color:OPS.dim}}>{es?'No hay billing codes con valor para estos filtros.':'No billing codes with value for these filters.'}</div>:byBilling.slice(0,10).map(b=><div key={b.code} style={{display:'grid',gridTemplateColumns:'1fr auto auto',gap:8,padding:'7px 0',borderTop:`1px solid ${OPS.border}`,alignItems:'center'}}><div style={{fontWeight:900,color:OPS.text,fontSize:12}}>{b.code}</div><div style={{fontSize:11,color:OPS.dim}}>{b.count} jobs</div><div style={{fontWeight:900,color:OPS.green}}>{money(b.value)}</div></div>)}</OpsCard><OpsCard><div style={{fontSize:15,fontWeight:900,color:OPS.text,marginBottom:8}}>❌ {es?'Motivos / frases más comunes':'Top failure phrases / reasons'}</div>{byReason.length===0?<div style={{fontSize:11,color:OPS.dim}}>{es?'No hay motivos en estos filtros.':'No reasons in these filters.'}</div>:byReason.map(r=><div key={r.reason} style={{display:'grid',gridTemplateColumns:'1fr auto',gap:8,padding:'7px 0',borderTop:`1px solid ${OPS.border}`,alignItems:'center'}}><div style={{fontSize:11,color:OPS.text}}>{r.reason}</div><div style={{fontWeight:900,color:OPS.red}}>{r.count}</div></div>)}</OpsCard></div>
    </div>

    <OpsCard><div style={{fontSize:15,fontWeight:900,color:OPS.text,marginBottom:8}}>📅 {es?'Segmentación por periodo':'Period breakdown'}</div>{byPeriod.length===0?<div style={{fontSize:11,color:OPS.dim}}>{es?'Sin datos.':'No data.'}</div>:<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:11}}><thead><tr>{['Period','Total','Completed','Not done','Pending','Value'].map(h=><th key={h} style={{textAlign:'left',padding:'8px 6px',borderBottom:`1px solid ${OPS.border}`,color:OPS.dim}}>{h}</th>)}</tr></thead><tbody>{byPeriod.map(r=><tr key={r.period}><td style={td}>{r.period}</td><td style={td}>{r.total}</td><td style={{...td,color:OPS.green,fontWeight:900}}>{r.completed}</td><td style={{...td,color:OPS.red,fontWeight:900}}>{r.notDone}</td><td style={{...td,color:OPS.yellow,fontWeight:900}}>{r.pending}</td><td style={{...td,color:OPS.green,fontWeight:900}}>{money(r.value)}</td></tr>)}</tbody></table></div>}</OpsCard>
    <style>{`@media(max-width:1050px){.tech-stats-filters{grid-template-columns:1fr 1fr!important}.tech-stats-main-grid{grid-template-columns:1fr!important}.tech-stats-tech-row{grid-template-columns:1fr repeat(2,70px)!important}} @media(max-width:640px){.tech-stats-filters,.tech-stats-tech-row{grid-template-columns:1fr!important}}`}</style>
  </div>;
}
function Metric({label,value,color}:{label:string;value:any;color:string}){ return <div style={{textAlign:'right'}}><div style={{fontWeight:900,color,fontSize:13}}>{value}</div><div style={{fontSize:8,color:OPS.dim,textTransform:'uppercase'}}>{label}</div></div>; }
