

const T = {
  es:{
    appName:"Guajiro&Sons",appSub:"ITG · Guajito&Sons · Miami-Dade & Broward",
    supLabel:"Supervisor",supDesc:"Acceso completo al sistema",
    techLabel:"Técnico",techDesc:"Ver mi ruta del día",
    supPin:"PIN de Supervisor",techNumLabel:"Número de Técnico",
    techPinLabel:"PIN",selectTech:"Seleccionar...",
    enter:"ENTRAR",verifying:"Verificando...",backBtn:"← Volver",
    wrongPin:"PIN incorrecto",wrongTechPin:"PIN incorrecto.",
    techNotFound:"Técnico no encontrado",selectFirst:"Selecciona tu número de técnico",
    noPinAssigned:"PIN no asignado. Contacta a tu supervisor.",
    selectRegion:"Selecciona tu región",miamiLabel:"Miami",swflLabel:"SW Florida",
    pinMgmtTab:"🔑 PINs",pinMgmtTitle:"Gestión de PINs",assignPin:"Asignar",changePin:"Cambiar",
    pinAssigned:"PIN asignado",noPin:"Sin PIN",savingPin:"Guardando...",pinSaved:"PIN actualizado",
    regionLabel:"Región",
    gpsOn:"GPS ON",closeDay:"Cerrar Día",exitBtn:"Salir",liveLabel:"Live",
    myRouteTab:"📍 Mi Ruta",reportTab:"📋 Reportar",techNotesTab:"✉️ Notas",
    techNoteTitle:"Enviar Nota al Supervisor",techNotePH:"Escribe tu mensaje...",techNoteSendBtn:"✈️ ENVIAR NOTA",techNoteSent:"✅ Nota enviada",techNoteHistory:"Mis notas de hoy",techNoteEmpty:"Sin notas enviadas hoy.",
    dayProgress:"Progreso del día",doneLabel:"Hechos",notDoneLabel:"No Hechos",pendingLabel:"Pendientes",
    totalEarned:"💰 Total a cobrar",noJobs:"No hay trabajos asignados para hoy.",
    supNotesTitle:"📋 Notas del Supervisor",loadingLabel:"Cargando ruta...",
    directionsBtn:"🗺️ Directions",callBtn:"📞 Llamar",photosBtn:"📷 Fotos",
    markDoneBtn:"✅ Hecho",markNotDoneBtn:"❌ No Hecho",
    payCodeLabel:"Código de pago:",confirmBtn:"✅ Confirmar",
    reasonLabel:"Razón:",savingLabel:"Guardando...",cancelBtn:"Cancelar",
    reportFormTitle:"📋 Reportar Trabajo No Completado",
    jobNumLabel:"Job Number *",addrLabel:"Dirección *",addrPH:"Dirección del trabajo",
    reasonRequired:"Razón *",notesLabel:"Notas",notesPH:"Detalles adicionales...",
    submitBtn:"✈️ ENVIAR REPORTE",sentTitle:"Reporte Enviado",
    sentDesc:"El supervisor fue notificado",newReportBtn:"Nuevo Reporte",
    photoModalTitle:"📷 Fotos",photoNoteLabel:"Nota para este trabajo",
    photoNotePH:"Observaciones, detalles...",uploadBtn:"📷 Seleccionar Fotos",
    uploadingLabel:"⏳ Subiendo...",noPhotosLabel:"No hay fotos aún.",readyBtn:"✅ Listo",
    eodTitle:"Reporte del Día",eodEarned:"💰 Total generado hoy",
    eodDoneSection:"✅ Trabajos Completados",eodNotDoneSection:"❌ No Completados",
    eodSendBtn:"📤 Enviar al Supervisor y Cerrar",
    resetPinLink:"¿Olvidaste o quieres cambiar tu PIN?",resetPinTitle:"Cambiar mi PIN",
    resetPinDesc:"Ingresa tu número de técnico y un nuevo PIN de 4 a 6 dígitos.",
    newPinLabel:"Nuevo PIN (4–6 dígitos)",newPinPH:"Ej: 1234",savePinBtn:"Guardar PIN",
    pinChangedOk:"PIN actualizado correctamente. Ya puedes iniciar sesión.",
    pinTooShort:"El PIN debe tener entre 4 y 6 dígitos numéricos.",
    sendAllSmsBtn:"📱 Avisar a todos los clientes",sendAllSmsDesc:"Envía mensaje de llegada a todos los clientes con teléfono registrado",
    smsSentCount:"Mensajes preparados:",smsNoPhones:"Ningún trabajo tiene teléfono registrado.",
    dashTab:"📊 Dashboard",routeTab:"📍 Ruta",mapTab:"🗺️ Técnicos",reportsTab:"📋 Reportes",notesTab:"💬 Notas",
    supPortalLabel:"🛡️ Portal Supervisor",jobControlTitle:"Control de Trabajos — Hoy",
    setBtn:"SET",totalAssignedLabel:"Total asignados",notCompletedLabel:"No completados",
    completedLabel:"Completados",pctCompletedLabel:"% completado",
    activeTechsLabel:"Técnicos activos",zonesLabel:"Zonas",
    todayReportsLabel:"Reportes hoy",inRoutesLabel:"En rutas",
    latestReportsTitle:"Últimos Reportes",techNotesSupTitle:"✉️ Notas de Técnicos",techNotesSupEmpty:"Sin notas de técnicos hoy.",downloadExcelBtn:"📥 DESCARGAR EXCEL",
    importRouteBtn:"📂 Importar Excel de Ruta",importingLabel:"⏳ Leyendo...",
    clearRouteBtn:"🗑️ Borrar Ruta",techsLabel:"Técnicos",totalJobsLabel:"Total jobs",
    addJobTitle:"➕ Agregar Trabajo de Última Hora",techNumShort:"Tech #",
    jobNumShort:"Job Number",cityLabel:"Ciudad",phoneLabel:"Teléfono",
    addJobBtn:"➕ Agregar Trabajo",noRouteMsg:"Importa un Excel de ruta para ver los trabajos.",
    mapTitle:"👷 Técnicos en Campo",techsFieldLabel:"Técnicos en campo",
    activeJobsLabel:"Jobs activos",noReportsMsg:"No hay reportes hoy.",
    sendNoteBtn:"📤 Enviar Nota",noteTypeLabel:"Tipo",forTechLabel:"Para Técnico (opcional)",
    allTechsLabel:"Todos los técnicos",noteContentLabel:"Mensaje",
    notePH:"Escribe la nota o instrucción...",todayNotesTitle:"Notas de Hoy",
    reportLangTitle:"Idioma del Reporte",cancelLang:"Cancelar / Cancel",
    excelLabel:"📥 Excel",
  },
  en:{
    appName:"Guajiro & Sons Field Suite v2.0",appSub:"ITG · Guajiro & Sons · Miami-Dade & Broward",
    supLabel:"Supervisor",supDesc:"Full system access",
    techLabel:"Technician",techDesc:"View my daily route",
    supPin:"Supervisor PIN",techNumLabel:"Tech Number",
    techPinLabel:"PIN",selectTech:"Select...",
    enter:"ENTER",verifying:"Verifying...",backBtn:"← Back",
    wrongPin:"Wrong PIN",wrongTechPin:"Wrong PIN.",
    techNotFound:"Technician not found",selectFirst:"Select your tech number",
    noPinAssigned:"PIN not assigned. Contact your supervisor.",
    selectRegion:"Select your region",miamiLabel:"Miami",swflLabel:"SW Florida",
    pinMgmtTab:"🔑 PINs",pinMgmtTitle:"PIN Management",assignPin:"Assign",changePin:"Change",
    pinAssigned:"PIN assigned",noPin:"No PIN",savingPin:"Saving...",pinSaved:"PIN updated",
    regionLabel:"Region",
    gpsOn:"GPS ON",closeDay:"Close Day",exitBtn:"Exit",liveLabel:"Live",
    myRouteTab:"📍 My Route",reportTab:"📋 Report",techNotesTab:"✉️ Notes",
    techNoteTitle:"Send Note to Supervisor",techNotePH:"Write your message...",techNoteSendBtn:"✈️ SEND NOTE",techNoteSent:"✅ Note sent",techNoteHistory:"My notes today",techNoteEmpty:"No notes sent today.",
    dayProgress:"Day progress",doneLabel:"Done",notDoneLabel:"Not Done",pendingLabel:"Pending",
    totalEarned:"💰 Total earned",noJobs:"No jobs assigned for today.",
    supNotesTitle:"📋 Supervisor Notes",loadingLabel:"Loading route...",
    directionsBtn:"🗺️ Directions",callBtn:"📞 Call",photosBtn:"📷 Photos",
    markDoneBtn:"✅ Done",markNotDoneBtn:"❌ Not Done",
    payCodeLabel:"Payment code:",confirmBtn:"✅ Confirm",
    reasonLabel:"Reason:",savingLabel:"Saving...",cancelBtn:"Cancel",
    reportFormTitle:"📋 Report Incomplete Job",
    jobNumLabel:"Job Number *",addrLabel:"Address *",addrPH:"Job address",
    reasonRequired:"Reason *",notesLabel:"Notes",notesPH:"Additional details...",
    submitBtn:"✈️ SUBMIT REPORT",sentTitle:"Report Submitted",
    sentDesc:"Supervisor was notified",newReportBtn:"New Report",
    photoModalTitle:"📷 Photos",photoNoteLabel:"Note for this job",
    photoNotePH:"Observations, details...",uploadBtn:"📷 Select Photos",
    uploadingLabel:"⏳ Uploading...",noPhotosLabel:"No photos yet.",readyBtn:"✅ Done",
    eodTitle:"Day Report",eodEarned:"💰 Total earned today",
    eodDoneSection:"✅ Completed Jobs",eodNotDoneSection:"❌ Not Completed",
    eodSendBtn:"📤 Send to Supervisor & Close",
    resetPinLink:"Forgot or want to change your PIN?",resetPinTitle:"Change my PIN",
    resetPinDesc:"Enter your tech number and a new 4–6 digit PIN.",
    newPinLabel:"New PIN (4–6 digits)",newPinPH:"e.g. 1234",savePinBtn:"Save PIN",
    pinChangedOk:"PIN updated successfully. You can now log in.",
    pinTooShort:"PIN must be 4–6 numeric digits.",
    sendAllSmsBtn:"📱 Notify all clients",sendAllSmsDesc:"Send arrival message to all clients with a phone number",
    smsSentCount:"Messages prepared:",smsNoPhones:"No jobs have a phone number on file.",
    dashTab:"📊 Dashboard",routeTab:"📍 Route",mapTab:"👷 Technicians",reportsTab:"📋 Reports",notesTab:"💬 Notes",
    supPortalLabel:"🛡️ Supervisor Portal",jobControlTitle:"Job Control — Today",
    setBtn:"SET",totalAssignedLabel:"Total assigned",notCompletedLabel:"Not completed",
    completedLabel:"Completed",pctCompletedLabel:"% completed",
    activeTechsLabel:"Active technicians",zonesLabel:"Zones",
    todayReportsLabel:"Today reports",inRoutesLabel:"In routes",
    latestReportsTitle:"Latest Reports",techNotesSupTitle:"✉️ Tech Notes",techNotesSupEmpty:"No tech notes today.",downloadExcelBtn:"📥 DOWNLOAD EXCEL",
    importRouteBtn:"📂 Import Daily Route Excel",importingLabel:"⏳ Reading...",
    clearRouteBtn:"🗑️ Clear Route",techsLabel:"Technicians",totalJobsLabel:"Total jobs",
    addJobTitle:"➕ Add Last-Minute Job",techNumShort:"Tech #",
    jobNumShort:"Job Number",cityLabel:"City",phoneLabel:"Phone",
    addJobBtn:"➕ Add Job",noRouteMsg:"Import a route Excel to see jobs per technician.",
    mapTitle:"👷 Technicians in Field",techsFieldLabel:"Techs in field",
    activeJobsLabel:"Active jobs",noReportsMsg:"No reports today.",
    sendNoteBtn:"📤 Send Note",noteTypeLabel:"Type",forTechLabel:"For Technician (optional)",
    allTechsLabel:"All technicians",noteContentLabel:"Message",
    notePH:"Write the note or instruction...",todayNotesTitle:"Today's Notes",
    reportLangTitle:"Report Language",cancelLang:"Cancel",
    excelLabel:"📥 Excel",
  },
};

const REGION_PINS:{[k:string]:string} = {miami:import.meta.env.VITE_SUP_PIN_MIAMI||'',swfl:import.meta.env.VITE_SUP_PIN_SWFL||''};

const REGION_LABELS:{[k:string]:{name:string,emoji:string,color:string,sub:string}} = {
  miami:{name:'Miami',emoji:'🌴',color:'#00b8f5',sub:'Miami-Dade & Broward'},
  swfl:{name:'SW Florida',emoji:'🌊',color:'#00dc85',sub:'Lee, Collier & Charlotte'},
};

const TECHS_MIAMI = [
  {id:"6017",name:"Rayner Hernandez",region:"miami"},{id:"6053",name:"Jorge Luis",region:"miami"},
  {id:"7010",name:"George Santiago",region:"miami"},{id:"7065",name:"Felix Roque",region:"miami"},
  {id:"7077",name:"Maykel Lopez Morales",region:"miami"},{id:"7102",name:"Yandy Gonzalez",region:"miami"},
  {id:"7113",name:"Vladimir Pujol",region:"miami"},{id:"7137",name:"Camilo Harrison",region:"miami"},
  {id:"7163",name:"Alberto Amaya",region:"miami"},{id:"7164",name:"Omar Bernton",region:"miami"},
  {id:"7191",name:"Wilfredo Herrera",region:"miami"},{id:"7235",name:"Bernal Hernandez",region:"miami"},
  {id:"7260",name:"Anier Villar",region:"miami"},{id:"7270",name:"Julio Florez",region:"miami"},
  {id:"7272",name:"Renier Gonzalez",region:"miami"},{id:"7377",name:"Alberto Denis Marichal",region:"miami"},
  {id:"7419",name:"Juan Guillermo Aranda",region:"miami"},{id:"7644",name:"Juan Trujillo",region:"miami"},
  {id:"7974",name:"Droo Pool",region:"miami"},{id:"8723",name:"Onil Perez",region:"miami"},
  {id:"8799",name:"Michel Santana",region:"miami"},{id:"8804",name:"Yunior Barba",region:"miami"},
  {id:"8807",name:"Idan Caballero",region:"miami"},
];

const TECHS_SWFL:{id:string,name:string,region:string}[] = [
  {id:"7004",name:"Antonio Alfonso Lopez",region:"swfl"},{id:"7006",name:"Marco Del Aguila",region:"swfl"},
  {id:"7009",name:"Jose Del Aguila",region:"swfl"},{id:"7011",name:"Antonio Montero Hernandez",region:"swfl"},
  {id:"7112",name:"Maria Angelica Buitrago",region:"swfl"},{id:"7133",name:"Yadiel Quintero Garcia",region:"swfl"},
  {id:"7176",name:"Michael Astrain Subiador",region:"swfl"},{id:"7225",name:"Cesar E Quinonez",region:"swfl"},
  {id:"7234",name:"Lazaro Prada Martinez",region:"swfl"},{id:"7255",name:"Dianesky S Echavarria H",region:"swfl"},
  {id:"7266",name:"Adrian Rengifo Enrique",region:"swfl"},{id:"7273",name:"Patrick Edward Jr Seymour",region:"swfl"},
  {id:"7284",name:"Yasmani Suares",region:"swfl"},{id:"7318",name:"Wilka Garcia Reyes",region:"swfl"},
  {id:"7325",name:"Yuniel Dorvigny D",region:"swfl"},{id:"7328",name:"Oscar Chacon Jerez",region:"swfl"},
  {id:"7348",name:"Daniel Seibert",region:"swfl"},{id:"7361",name:"Jose Alfredo Aguila Ulloa",region:"swfl"},
  {id:"7368",name:"Michel Ontivero Diaz",region:"swfl"},{id:"7373",name:"Javier Gonzalo Hernandez Ladino",region:"swfl"},
  {id:"7374",name:"Pedro Luis Argudin Mojena",region:"swfl"},{id:"7395",name:"Stephano Diaz Hernandez",region:"swfl"},
  {id:"7644",name:"Juan Alberto Trujillo Diaz",region:"swfl"},{id:"7708",name:"Eloy Suarez Mouriz",region:"swfl"},
  {id:"7754",name:"Erick Rodriguez Pasto",region:"swfl"},{id:"8072",name:"Edey Ladron De Guevara",region:"swfl"},
  {id:"8159",name:"Juan Torres Mitjans",region:"swfl"},{id:"8377",name:"Luis Acosta Valdes",region:"swfl"},
  {id:"8405",name:"Maikel Garcia Moreno",region:"swfl"},{id:"8514",name:"Jose Torres Padron",region:"swfl"},
];

const TECHS = [...TECHS_MIAMI,...TECHS_SWFL];

const getTechsByRegion=(region:string)=>region==='swfl'?TECHS_SWFL:TECHS_MIAMI;

const PAY_CODES = [
  {code:"601",label:"601 — 0-300ft",total:100},
{code:"873",label:"873 — Sin tubería",total:45},
  {code:"874",label:"874 — 300-400ft",total:130},
  {code:"875",label:"875 — 400-500ft",total:160},
  {code:"876",label:"876 — 500-600ft",total:200},
  {code:"877",label:"877 — 600-700ft",total:200},
  {code:"878",label:"878 — 700-800ft",total:200},
  {code:"879",label:"879 — 800-900ft",total:200},
  {code:"D10",label:"D10 — 1000-1100ft",total:250},
  {code:"D15",label:"D15 — 1100-1200ft",total:250},
  {code:"D20",label:"D20 — 1200ft+",total:300},
  {code:"SQFT",label:"Corte por sqft",total:0,needsFt:true,unit:"sqft"},
  {code:"CRUCE",label:"Cruce de calle",total:0,needsFt:true,unit:"ft"},
];

const REASONS_LIST = [
  {id:"aerial",label:"Aéreo",emoji:"🔌",color:"#ff5a1f"},
  {id:"gate",label:"Gate Cerrado",emoji:"🔒",color:"#ff3348"},
  {id:"absent",label:"Customer Ausente",emoji:"🏠",color:"#9d5fff"},
  {id:"811",label:"Necesita 811",emoji:"⚠️",color:"#ffbe00"},
  {id:"nocut",label:"No Quiere Corte",emoji:"🚫",color:"#f43f5e"},
  {id:"hoa",label:"Permiso HOA",emoji:"🏢",color:"#8b5cf6"},
  {id:"missile",label:"Necesita Misil",emoji:"🎯",color:"#06b6d4"},
  {id:"machine",label:"Requiere Máquina",emoji:"🚜",color:"#f97316"},
  {id:"twomen",label:"Requiere 2 Técnicos",emoji:"👥",color:"#10b981"},
  {id:"neighbor",label:"Vecino No Disponible",emoji:"🏘️",color:"#64748b"},
  {id:"cancelled",label:"Cliente Canceló",emoji:"❌",color:"#ff3348"},
  {id:"notime",label:"No Me Dio el Tiempo",emoji:"⏰",color:"#eab308"},
  {id:"construct",label:"En Construcción",emoji:"🏗️",color:"#a78bfa"},
  {id:"obstacle",label:"Obstáculo / Bloqueo",emoji:"🚧",color:"#00e0d4"},
  {id:"duplicate",label:"Duplicado / Ya Hecho",emoji:"✅",color:"#22d3ee"},
  {id:"mdu",label:"MDU",emoji:"🏗️",color:"#0ea5e9"}, {id:"other",label:"Otro",emoji:"📝",color:"#5a7aaa"},
];

const NOTE_TYPES = {
  recommendation:{label:"Recomendación",color:"#00dc85",bg:"#00dc8518",border:"#00dc8544",icon:"💡"},
  mandatory:{label:"Obligatorio",color:"#ff3348",bg:"#ff334818",border:"#ff334844",icon:"🚨"},
  urgent:{label:"URGENTE",color:"#ffbe00",bg:"#ffbe0018",border:"#ffbe0044",icon:"⚡"},
};

const getTechName = (id:string) => TECHS.find(t => t.id === String(id))?.name || String(id);

export { T, REGION_PINS, REGION_LABELS, TECHS_MIAMI, TECHS_SWFL, TECHS, getTechsByRegion, PAY_CODES, REASONS_LIST, NOTE_TYPES, getTechName };
